languageCode: "en-us"
baseUrl: "https://sy1.sh"
title: "0x73796C31"
paginate: 10
theme: "PaperMod"
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 1
  - identifier: cv
    name: About
    title: CV
    url: cv
    weight: 2
  - identifier: writeups
    name: Write-ups
    title: Write-ups
    url: /writeups/
    weight: 3

outputs:
  home:
    - HTML
    - RSS
    - JSON 

params:
  author: "Dimitar Ganev"
  email: dganev@pm.me
  description: ""
  paginationSinglePost: true
  ShowReadingTime: true
  ShowToc: true
  TocOpen: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  hideSummary: true

  profileMode:
    enabled: true
    Title: "archive://sy1.sh"
    Content: >
        - This website is my research archive; 
        I am trying my best to keep the information consistent and correct, 
        but some of it might be wrong. You can always suggest an edit on 
        anything that you think isn't correct.

  socialIcons:
    - name: github
      url: "https://github.com/syrull"
    - name: linkedin
      url: "https://www.linkedin.com/in/dimitar-ganev-syl-/"

markup:
  goldmark:
    renderer:
      unsafe: true